# Generated by Django 5.2.4 on 2025-07-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_exam_examattempt_examquestion_examchoice_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='parent_mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_mobile',
        ),
    ]
