# Generated by Django 5.2.4 on 2025-07-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Your age (optional)', null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='help_text',
            field=models.TextField(blank=True, help_text='Tell us how you can help us (optional)', null=True, verbose_name='How can you help us?'),
        ),
    ]
